### ISSUE TITLE
Parse .vec results to .JSON files

### ISSUE THREAD

**Issue by tabaddor** [VeReMi-dataset/VeReMi-popper#1]
What scripts are used after finishing a simulation in veins (which results in a `.vec` and `.sca` files), to create the `JSON` logs for each vehicle, as well as the Ground Truth log?

**Comment by Enough7** [comment]
@tabaddor Did find out which scripts were used?

**Comment by tabaddor** [comment]
Not for this repo. I ended up using: https://github.com/josephkamel/veins-f2md.
